---

# Ensure that logrotate is installed
- name: Check logrotate installed
  apt: name=logrotate update_cache=yes

# Load template for log rotation

- name: Adding config to logrotate.d
  template: src=syslog-ng.j2 dest=/etc/logrotate.d/syslog-ng
