---
#
# Installing Elasticsearch
#
# Adds the apt-key for Elasticsearch
- name: Add Elasticsearch apt-key
  apt_key: url="https://packages.elastic.co/GPG-KEY-elasticsearch" state=present

# Add the Elasticsearch APT-repository
- name: Adding Elasticsearch APT repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/5.x/apt stable main
    state: present

# Install Elasticsearch
- name: Update repositories cache and install Elasticsearch
  apt: name=elasticsearch update_cache=yes

# Load ES config file
- name: Loading config file from template
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=elasticsearch group=elasticsearch mode=0755
  notify: restart es

# Enable ES service
- name: Enabling ES service
  systemd: name=elasticsearch enabled=yes daemon_reload=yes

#### Start ES service
- name: Starting ES service
  systemd: name=elasticsearch state=started
