---
- name: Install ELK, Java and syslog-ng
  hosts: elk
  remote_user: elk
  become: yes
  become_method: sudo
  roles: 
    - { role: java, tags: java }
    - { role: elasticsearch, tags: es }
    - { role: kibana, tags: kibana }
    - { role: syslog-ng, tags: syslog-ng }
    - { role: logstash, tags: logstash }
    - { role: curator, tags: curator }
    - { role: logrotate, tags: logrotate }	
