---
# Installing logstash
#

# Add Logstash APT repository
- name: Adding logstash APT repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/5.x/apt stable main
    state: present

# Installing Logstash
- name: Update repositories cache and install Logstash
  apt: name=logstash update_cache=yes

# Configure  configuration
- name: Configure configuration file
  template: src=simple.conf.j2 dest=/etc/logstash/conf.d/simple.conf owner=root group=root mode=0644
  notify: restart logstash

# Start Logstash service
- name: Start Logstash service
  systemd: name=logstash state=started daemon_reload=yes

# Enable Logstash service
- name: Enable Logstash service
  systemd: name=logstash enabled=yes
